driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/lumberjack']

provisioner:
  require_chef_omnibus: 11.12.8

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
      - recipe[golang::default]
      - recipe[omnibus::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
      - recipe[golang::default]
  - name: ubuntu-10.04
    run_list:
      - recipe[apt::default]
      - recipe[golang::default]
  - name: centos-5.10
      - recipe[golang::default]
  - name: centos-6.5
      - recipe[golang::default]

suites:
  - name: default
    run_list:
      - omnibus::default
    attributes:
      omnibus:
        build_user: vagrant
        build_dir: /home/vagrant/lumberjack
        install_dir: /opt/lumberjack
      go:
        version: 1.3

